### ISSUE TITLE
서버 점검 공지

### ISSUE THREAD

**Issue by SightStudio** [TASK-FORCE/super-invention#419]
2021.09.16에 이사를 갑니다.

이에 따라 지금 제 발밑에 있는 만날까 서버가 2021.09.15에 잠시 중단이 될 예정입니다.

한 일주일 정도 걸리지 않을까 싶음? 

![image](https://user-images.githubusercontent.com/50672087/131987863-434e6ddc-78c1-4f77-a436-6dd4bd12f131.png)

**Comment by yyy9942** [comment]
@SightStudio 서버 설정 부탁드립니다.

**Comment by SightStudio** [comment]
서버 설정 완료되었습니다
